name: Python lint, build Docker image, and push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run linter
      run: pylint .

    - name: Build Docker image
      run: docker build -t my-python-app .

    - name: Log in to Docker Hub
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

    - name: Tag Docker image
      run: docker tag my-python-app "dmitryshitov/my-python-app:latest"

    - name: Push Docker image to Docker Hub
      run: docker push "dmitryshitov/my-python-app:latest"

    - name: Send email notification
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'GitHub Actions Pipeline Finished'
        to: 'shitovdmt@yandex.ru'
        body: 'Your GitHub Actions pipeline has finished successfully.'

